# Generated by Django 6.0.2 on 2026-05-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_shipping_coupon_code_order_shipping_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='facility_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
