# Generated by Django 6.0.2 on 2026-05-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='facility_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
