# Generated by Django 6.0.2 on 2026-05-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_shippingaddress_facility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='contact_person',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
