# Generated by Django 6.0.2 on 2026-05-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_shippingaddress_contact_person_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
